//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suftnet.Cos.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\Branches\\Suftnet.Web\\12.500\\Suftnet." +
            "Cos\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf;Integrated Security=True;User Instance=Tr" +
            "ue")]
        public string SuftnetDbConnectionString {
            get {
                return ((string)(this["SuftnetDbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\Branches\\Suftnet.Web\\12.500\\Suftnet." +
            "OnlineHotel\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf;Integrated Security=True;User Ins" +
            "tance=True")]
        public string SuftnetDbConnectionString1 {
            get {
                return ((string)(this["SuftnetDbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\Branches\\Suftnet.Web\\12.500\\Suftnet." +
            "Hotels.StandAlone\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf;Integrated Security=True;Us" +
            "er Instance=True")]
        public string SuftnetDbConnectionString2 {
            get {
                return ((string)(this["SuftnetDbConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"D:\\Branches\\Suftnet.Web\\12.500\\Suftnet" +
            ".Church.StandAlone -Beta1.01\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf\";Integrated Secu" +
            "rity=True;User Instance=True")]
        public string SuftnetDbConnectionString3 {
            get {
                return ((string)(this["SuftnetDbConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"D:\\Branches\\Suftnet.Web\\12.500\\Suftnet" +
            ".Stock.StandAlone -Beta1.01\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf\";Integrated Secur" +
            "ity=True;User Instance=True")]
        public string SuftnetDbConnectionString4 {
            get {
                return ((string)(this["SuftnetDbConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"D:\\Branches\\Suftnet.Web\\12.500\\Suftnet" +
            ".Stock.StandAlone -Beta1.0.1\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf\";Integrated Secu" +
            "rity=True;User Instance=True")]
        public string SuftnetDbConnectionString5 {
            get {
                return ((string)(this["SuftnetDbConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\Branches\\Suftnet.Web\\12.500\\Suftnet." +
            "Church.StandAlones-Beta1.0.2\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf;Integrated Secur" +
            "ity=True;User Instance=True")]
        public string SuftnetDbConnectionString6 {
            get {
                return ((string)(this["SuftnetDbConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\LinqtoSql\\Database\\Suft" +
            "netDbcc.mdf;Integrated Security=True;User Instance=True")]
        public string dbconnectionString {
            get {
                return ((string)(this["dbconnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Visual Studio\\Branch\\4.2015\\Suftnet" +
            ".Church.StandAlones-Beta1.0.2\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf\";Integrated Sec" +
            "urity=True;User Instance=True")]
        public string SuftnetDbConnectionString7 {
            get {
                return ((string)(this["SuftnetDbConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=OneChurch;Integrated Security=True")]
        public string OneChurchConnectionString {
            get {
                return ((string)(this["OneChurchConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Visual Studio\\Branch\\4.2015\\Suft" +
            "net.Church.StandAlones-Beta1.0.2\\Suftnet.Cos\\App_Data\\SuftnetDb.mdf\";Integrated " +
            "Security=True")]
        public string SuftnetDbConnectionString8 {
            get {
                return ((string)(this["SuftnetDbConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=b0o6p8bxhu.database.windows.net;Initial Catalog=iadmin;User ID=Kcmkcm" +
            "@b0o6p8bxhu;Connect Timeout=60")]
        public string iadminConnectionString {
            get {
                return ((string)(this["iadminConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=75.125.28.187,1750;Initial Catalog=DB1609_Suftnet;User ID=DB1609_Admi" +
            "n;Password=kcmkcm123")]
        public string DB1609_SuftnetConnectionString {
            get {
                return ((string)(this["DB1609_SuftnetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=b0o6p8bxhu.database.windows.net;Initial Catalog=iadmin;User ID=Kcmkcm" +
            "@b0o6p8bxhu;Password=Aa123!!!;Connect Timeout=60")]
        public string iadminConnectionString1 {
            get {
                return ((string)(this["iadminConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=eAdmin;Integrated Security=True")]
        public string eAdminConnectionString {
            get {
                return ((string)(this["eAdminConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\;Initial Catalog=iChurch;Integrated Security=True")]
        public string iChurchConnectionString {
            get {
                return ((string)(this["iChurchConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OV3KHAM;Initial Catalog=iChurch;Integrated Security=True")]
        public string iChurchConnectionString1 {
            get {
                return ((string)(this["iChurchConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=iChurch;Integrated Security=True")]
        public string iChurchConnectionString2 {
            get {
                return ((string)(this["iChurchConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql6002.smarterasp.net;Initial Catalog=DB_A28530_ichurch;User ID=DB_A" +
            "28530_ichurch_admin")]
        public string DB_A28530_ichurchConnectionString {
            get {
                return ((string)(this["DB_A28530_ichurchConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql6002.smarterasp.net;User ID=DB_A28530_ichurch_admin;Password=Kcmkc" +
            "m12345!")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
            }
        }
    }
}
